#!/usr/bin/env python3
"""Score a wider space of candidate P with the scheduler's model.

usage: cand_explore.py [--state DIR] [--workers K] [--tau-min A] [--tau-max B]

Generates candidates outside gen_candidates' ranges (no factor 7, squared
big primes, 23, larger exponents of 2, non-monotone exponents), computes
S_min and the vector counts near it for each (cached in the state's
pinfo), and prints the best by the scheduler's prior score, marking which
would already be generated by gen_candidates.
"""
import argparse
import itertools
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import scheduler as sc


def wide_candidates(tau_min, tau_max):
    out = set()
    for e2 in range(6, 25):
        for e3 in range(2, 13):
            for e5 in range(0, 8):
                for e7 in range(0, 6):
                    base = [e2, e3, e5, e7]
                    # tails over 11, 13, 17, 19, 23: exponents 0-2 for 11, 13 and
                    # 0-1 for 17, 19, 23, at most 3 nonzero
                    for t11, t13 in itertools.product(range(3), range(3)):
                        for t17, t19, t23 in itertools.product(range(2), range(2), range(2)):
                            tail = [t11, t13, t17, t19, t23]
                            if sum(1 for t in tail if t) > 3:
                                continue
                            P = sc.norm_p(base + tail)
                            if not P or len(P) > len(sc.PRIMES):
                                continue
                            if sc.p_value(P) >= 2 ** 63:
                                continue
                            t = sc.tau(P)
                            if tau_min <= t <= tau_max:
                                out.add(P)
    return out


def ext_candidates(tau_min, tau_max):
    """gen_candidates' families with wider exponent ranges (the plan's top
    units sit at e3 = 9 and e5 = 6, the current upper limits)"""
    out = set()
    for e2 in range(8, 23):
        for e3 in range(3, 13):
            if e3 > e2:
                continue
            for e5 in range(2, 9):
                if e5 > e3:
                    continue
                for e7 in range(1, 6):
                    if e7 > e5:
                        continue
                    for mask in range(16):
                        tail = [(mask >> i) & 1 for i in range(4)]
                        if sum(tail) > 2:
                            continue
                        P = sc.norm_p([e2, e3, e5, e7] + tail)
                        if sc.p_value(P) >= 2 ** 63:
                            continue
                        if tau_min <= sc.tau(P) <= tau_max:
                            out.add(P)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--state", default=os.path.join(sc.ROOT, "data", "sched"))
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--tau-min", type=int, default=600)
    ap.add_argument("--tau-max", type=int, default=20000)
    ap.add_argument("--limit", type=int, default=0, help="at most this many new P (0 = all)")
    ap.add_argument("--sample", type=int, default=0, help="random sample of this many new P")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--mode", default="wide", choices=["wide", "ext"])
    ap.add_argument("--top", type=int, default=60)
    a = ap.parse_args()
    args = argparse.Namespace(state=a.state, vec_size=6, workers=a.workers, unit_time=120,
                              node_limit=20_000_000_000, tau_min=800, tau_max=12000,
                              active=1, only=None, no_legacy=False)
    sch = sc.Scheduler(args)
    std = set(sc.gen_candidates(6, 800, 12000))
    wide = (wide_candidates if a.mode == "wide" else ext_candidates)(a.tau_min, a.tau_max)
    new = sorted(wide - std)
    if a.limit:
        new = new[:a.limit]
    if a.sample and a.sample < len(new):
        import random
        random.Random(a.seed).shuffle(new)
        new = sorted(new[:a.sample])
    sc.log(f"{len(std)} standard candidates, {len(wide)} wide, {len(new)} new to score")
    cands = sorted(std | set(new))
    scorer = sc.Scorer(sch.model, sch.results, sch.pinfo)
    sch.prepare(cands, scorer)
    sch.pinfo.save()
    scored = []
    for P in cands:
        try:
            s = scorer.prior(P)
        except Exception as e:  # noqa
            s = 0.0
        d = sch.pinfo.data.get(sch.pinfo.key(P), {})
        scored.append((s, P, d.get("smin", 0)))
    scored.sort(reverse=True)
    print(f"{'rank':>4} {'P':22} {'tau':>6} {'S_min':>6} {'magic/CPU-year':>14}  std?")
    for i, (s, P, smin) in enumerate(scored[:a.top]):
        print(f"{i + 1:4} {sc.p_str(P):22} {sc.tau(P):6} {smin:6} {s * 3.15e7:14.3g}  {'std' if P in std else 'NEW'}")
    # how much do the new ones add among the top K?
    for K in (50, 100, 200, 500, 1000):
        top = scored[:K]
        nn = sum(1 for s, P, _ in top if P not in std)
        tot = sum(s for s, P, _ in top)
        tn = sum(s for s, P, _ in top if P not in std)
        print(f"top {K:5}: {nn:4} new ({100 * tn / max(tot, 1e-30):.0f}% of the score mass)")
    # score mass by family
    fam = {}
    for s, P, _ in scored:
        key = ("no7" if len(P) < 4 or P[3] == 0 else "7") + "/" + \
              ("sq-big" if any(e >= 2 for e in P[4:]) else "lin-big") + "/" + \
              f"k={sum(1 for e in P if e)}"
        f = fam.setdefault(key, [0, 0.0])
        f[0] += 1
        f[1] += s
    print("\nfamily: count, total prior score (magic/CPU-year summed)")
    for key, (n, s) in sorted(fam.items(), key=lambda kv: -kv[1][1]):
        print(f"  {key:22} {n:5} {s * 3.15e7:12.3g}")


if __name__ == "__main__":
    main()
